### ISSUE TITLE
ChatQnA helm deployment doesn't support chatqna-ui

### ISSUE THREAD

**Issue by kushal2705** [opea-project/GenAIInfra#254]
While deploying ChatQnA with helm its found that chatqna-ui pod isn't deployed. In absence of chatqna-ui, only `curl` commands can be used to validate ChatQnA, kindly enhance ChatQnA helm for chatqna-ui support.

**Comment by Ruoyu-y** [comment]
@kushal2705 For now, we decided to first NOT make the UI deployment part of the ChatQnA helm chart/pipeline because of issue https://github.com/opea-project/GenAIExamples/issues/518. And i have raised a PR https://github.com/opea-project/GenAIInfra/pull/316 to include the steps of UI deployment within the helm chart readme. Can you try with that? 
And once the issue of UI has been resolved, we will include the UI as part of the helmchart.

**Comment by lianhao** [comment]
@kushal2705 PR #377 has added the ui support in ChatQnA helm chart. Please check out the latest code and readme. Thx!

**Comment by lianhao** [comment]
closes this since it's already supported
