### ISSUE TITLE
helm-chart/common/chatqna-ui refers to docker image opea/chatqna-conversation-ui but this does not exist on docker hub

### ISSUE THREAD

**Issue by SeanCondon** [opea-project/GenAIInfra#276]
Hi I am in the ITEP development group along with @kushal2705 
I'm trying out the chatqna-conversation-ui but it refers to this unknown version - I've tried the 0.7 and latest and while the UI opens it cannot send a POST request to the backend

**Comment by lianhao** [comment]
We assumed the public container image v0.8 on docker hub should be available soon after the v0.8 release(released at end of July), unfortunately it's not the case.

As for your UI specific issue, because of the issue opea-project/GenAIExamples#493 and opea-project/GenAIExamples#518, you have to manually build the UI docker image by yourselves at this time. 

@Ruoyu-y Could you please provide some workaround guide on how to make UI working before the above 2 issues are resolved? Thanks!

**Comment by SeanCondon** [comment]
I created a PR #305 that adjusts the helm chart to make the backend configurable at deploy time.
It creates a reverse proxy in nginx that points to the backend. The UI then points to this reverse proxy using a relative path e.g. `/chatqna/v1/chatqna` 

In this case I build the UI with
```bash
docker build --platform=linux/amd64 --no-cache -t opea/chatqna-conversation-ui:itep-build --build-arg https_proxy=$https_proxy --build-arg http_proxy=$http_proxy --build-arg BACKEND_SERVICE_ENDPOINT=/chatqna/v1/chatqna --build-arg DATAPREP_SERVICE_ENDPOINT=/chatqna-data-prep/v1/dataprep -f ./docker/Dockerfile.react .
```

**Comment by lianhao** [comment]
I believe the docker image is published and CORS issue is fixed
