### ISSUE TITLE
[Feature][helm-charts] Expose service account 

### ISSUE THREAD

**Issue by poussa** [opea-project/GenAIInfra#532]
In order to make OPEA deployments easier and more secure the service account (SA) needs to be exposed to deployments. Especially to those accessing the model data (e.g. tgi). In CSP environments (e.g. Google cloud), the model data is often stored in a cloud service (e.g., Google Cloud Storage (gcs)). Pod access to these services are managed via SAs. Special SAs are created and granted access. We don't want to use `default` SA since it gives all pods access, which is unnecessary. 

Currently, there is no way to set the SA for any deployments. 

In general, it would be good if all the helm charts settings are based on what comes out from `helm create`. The settings are there for a reason.

**Comment by eero-t** [comment]
@poussa Was the intention of this ticket that all the apps and components need to have their own _separate_ SA options, or were you thinking of those being grouped somehow (or even global)?

I'm asking because @lianhao's PRs linked to this  (which look fine) implement former.  However, if one would want to configure SAs for all of them, that's a *lot* of Helm variables one needs set...

**Comment by poussa** [comment]
We don't need all charts to have separate SA, that is an overkill. One per namespace is enough, which translates to one per example app. Let's start with that.
